### ISSUE TITLE
Problem with rgistration link

### ISSUE THREAD

**Issue by Ilde92** [qiskit-community/quantum-explorers#1]
Hello,
registration should be open now, right? But if I follow the link I get "404 not found". Why is that?
Thanks

**Comment by quantum-kittens** [comment]
@Ilde92 Thank you. There was a typo in the url in the ReadMe, it's now been fixed. Yes, registration opened on August 1 and is still open.

Please head to [http://qisk.it/quantum-explorers](http://qisk.it/quantum-explorers).
